### PR TITLE
Matchers for Joda-Time temporals

### PR DESCRIPTION
**Pull request by tnaskali**
Support for Joda-Time LocalDate, LocalDateTime, LocalTime and DateTime (compile-only non-transitive dependency to joda-time)

### CODE REVIEW

**Comment by stewbis** [comment]
This library is for core java types only and not joda time. I'd recommend creating a new library called hamcrest-joda-time to host the joda time matchers.

**Comment by tnaskali** [comment]
This seems like a better option indeed. What about creating a "core" generic library and two implementations that depend on it, java and joda-time ?

**Comment by stewbis** [comment]
Hi, really sorry for not getting back sooner and yes the split to a core lib with java and joda implementations _may_ make sense. Before the split though - are you able to raise a PR or create a branch of master with just the changes to support Joda so I can see the extent of the change. This PR contains all the changes for the zone change as well so it's hard to see the scope of the change. If the change looks clean I can look at doing the split in a branch. Regards, Stewart

**Comment by tnaskali** [comment]
Hi Stewart, I tried to package all the code to support Joda under the `org.exparity.hamcrest.date.joda` package. All the other changes should be related to time zone support. In the meantime I'll try to split them into two separate branches / PRs. Thomas

**Comment by stewbis** [comment]
Hi Thomas, If it's all under the org.exparity.hamcrest.date.joda package then that's cool. I'll pull the PR down and review the diff. No need for you to split it out.

**Comment by stewbis** [comment]
I've re-opened the PR but into a new branch called joda-time.

**Pull request closed without merging**
